uxapp/stock/routes.py
from ast import Assign
from unicodedata import category, name
from flask import Blueprint, redirect, render_template, request, session, url_for, flash
from flask_login import login_required
from uxapp.models import Agents, Stock_cat, Stock, Orders,Orderingitems
from uxapp import db

stock_routes = Blueprint('stock_routes', __name__)

#=========================
# Stock Categories Route
#=========================
@stock_routes.route("/stock" , methods=['GET', 'POST'])
@login_required
def stock():
    if request.method == "POST":
        if 'add-cat' in request.form:
            categ = request.form['categ']
            categ_icon = request.form.get('icon')
            categ_qu = Stock_cat.query.filter_by(categ = categ)
            if categ_qu is None:
                flash('Category Is Already Exist In Table', 'alert-danger')
            else:
                categ_qu = Stock_cat(categ = categ, cat_icon= categ_icon)
                db.session.add(categ_qu)
                db.session.commit()
                flash('Category Added', 'alert-success')
                return redirect(url_for('stock_routes.stock'))
        elif 'edit-cat' in request.form:
            categ_id = request.form['cat-id']
            categ = request.form['categ']
            categ_icon = request.form.get('icon')
            cat = Stock_cat.query.filter_by(id = categ_id).first()
            try:
                cat.categ = categ
                cat.cat_icon= categ_icon
                db.session.commit()
                flash('Category Updated', 'alert-success')
                return redirect(url_for('stock_routes.stock'))
            except:
                flash('Error: Please Try Again', 'alert-danger')
                return redirect(url_for('stock_routes.stock'))
        elif 'delete-cat' in request.form:
            categ_id = request.form['delete-cat']
            cat = Stock_cat.query.filter_by(id = categ_id).first()
            db.session.delete(cat)
            db.session.commit()
            flash('Category Deleted', 'alert-success')
            return redirect(url_for('stock_routes.stock'))
    stock_categs = Stock_cat.query.order_by(Stock_cat.id)
    return render_template("/stock/stock.html", title="Stock", stocka="active", stock_categs = stock_categs, Stock = Stock)
#=========================
# View Stock Item Route
#=========================
@stock_routes.route("/stock/stock-item-cate/<int:st_item>" , methods=['GET', 'POST'])
@login_required
def stockItem(st_item):
    if Stock_cat.query.filter_by(id = st_item).first() == None: # Check If Category is Exist or redirect to 404 page
        return render_template('404.html'), 404
    elif request.method == "POST":
        if Agents.query.filter_by(bio = request.form['add-assi']).first() != None: # check if agent is exist first in HC
            assign_agent = Agents.query.filter_by(bio = request.form['add-assi']).first().id
        elif request.form['add-assi'] == '':
            assign_agent = None
        else:
            assign_agent = None
            flash('The Agent you try to assign Not Found On HeadCount', 'alert-warning')
        try:
            stockItem = request.form['stockItem']
            serial = request.form['add-serial']
            quantity = request.form['add-quantity'] or 0
            pos = request.form['add-pos']
            comm = request.form['add-comm']
            add_item = Stock(item_name = stockItem, serial = serial, quantity = quantity, position = pos, assigned_to = assign_agent ,comment = comm, stock_categ = st_item)
            db.session.add(add_item)
            db.session.commit()
            flash('Item Added', 'alert-success')
        except:
            flash('Something went wrong, please make sure you intered valid values', 'alert-danger')
    stock_categs_items = Stock.query.filter_by(stock_categ = st_item).all()
    stock_item_cat = Stock_cat.query.filter_by(id = st_item).first()
    return render_template("/stock/stock-item.html", title="Stock Item",stocka="active", stock_categs_items = stock_categs_items, stock_item_cat=stock_item_cat)
#=========================
# Edit Stock Item Route
#=========================
@stock_routes.route("/stock/stock-edit" , methods=['GET', 'POST'])
@login_required
def stockItemEdit():
    if request.method == "POST":
        prev_url = request.referrer
        item_id = request.form['edit-id']
        cat_id = request.form.get('cat-id')
        stockItem = request.form['stockItem']
        serial = request.form['add-serial']
        quantity = request.form['add-quantity'] or 0
        pos = request.form['add-pos']
        comm = request.form['add-comm']
        itemToEdit = Stock.query.get_or_404(item_id)
        if Agents.query.filter_by(bio = request.form['edit-assi']).first() != None: # check if agent is exist first in HC
            assign_agent = Agents.query.filter_by(bio = request.form['edit-assi']).first().id
        elif request.form['edit-assi'] == '':
            assign_agent = None
        else:
            assign_agent = None
            flash('The Agent you try to assign Not Found On HeadCount', 'alert-warning')
        try:
            itemToEdit.item_name = stockItem
            itemToEdit.serial = serial
            itemToEdit.quantity = quantity
            itemToEdit.position = pos
            itemToEdit.comment = comm
            itemToEdit.assigned_to = assign_agent
            db.session.commit()
            flash('Item Updated', 'alert-success')
            return redirect(prev_url)
        except:
            return redirect(prev_url)
    else:
        flash('Something went wrong, please make sure you intered valid values', 'alert-danger')
        return redirect(request.referrer)
#=========================
# Delete Stock Item Route
#=========================
@stock_routes.route("/stock/stock-delete" , methods=['GET', 'POST'])
@login_required
def stockItemDelete():
    if request.method == "POST":
        item_id = request.form['delete-id']
        try:
            delete_item = Stock.query.get(item_id)
            db.session.delete(delete_item)
            db.session.commit()
            flash('Item Deleted', 'alert-success')
            return redirect(request.referrer)
        except:
            flash('Something went wrong, please make sure you intered valid values', 'alert-danger')
            return redirect(request.referrer)
    else:
        return redirect(request.referrer)

#=========================
# Stock In and Out Route
#=========================
@stock_routes.route("/stock-orders" , methods=['GET', 'POST'])
@login_required
def stock_orders():
    if request.method == 'POST':
        delv_title = request.form['delv-title']
        delv_date = request.form['delv-date'] 
        add_delv_note = Orders(title = delv_title, date = delv_date)
        db.session.add(add_delv_note)
        db.session.flush()
        db.session.commit()
        flash('Addes Successfully', 'alert-success')
        return redirect(url_for('stock_routes.stock_add_order', order_id= add_delv_note.id))
    orders = Orders.query.order_by(Orders.id)
    return render_template("/stock/stock-orders.html", title="Stock Orders",stockinout="active", orders = orders)
#==================================
# Stock Orders {Order Items View}
#==================================
@stock_routes.route("/view-order/<int:order_id>" , methods=['GET', 'POST'])
@login_required
def stock_order_view(order_id):
    print(order_id)
        
        
    return render_template('/stock/stock-view-order.html', title="Order Items",stockinout="active", order_id= order_id)

#=========================
# Stock Orders {Order Items Edit}
#=========================
@stock_routes.route("/add-order/<int:order_id>" , methods=['GET', 'POST'])
@login_required
def stock_add_order(order_id):
    if request.method == 'POST':
        item_category = request.form.getlist('item-category')
        item_name = request.form.getlist('item-name')
        item_serial = request.form.getlist('item-serial')
        item_quantity = request.form.getlist('item-quantity')
        for category, name, serial, quantity in zip(item_category, item_name, item_serial, item_quantity):
            # add_to_items = Orderingitems(deliveryNote = order_id, quantity = quantity)
            get_stock_item = Stock(item_name = name, serial = serial, quantity = quantity,stock_categ = int(category))
            db.session.add(get_stock_item)
            db.session.flush()
            item_id = Stock(Stockstock_order = get_stock_item.id)
            db.session.add(item_id)
            db.session.commit()
            print(category, name, serial, quantity)
    
    categories = Stock_cat.query.order_by(Stock_cat.id)    
    return render_template('/stock/stock-add-order.html', title="Add New Order",stockinout="active", categories = categories)

uxapp/templates/stock/stock-add-order.html
<!-- Orders Boared Template -->
{% extends "dashboard.html" %}
{% block in_dashboard %}
<section class="orders-boared">
    <div class="col-md-12">
         <!-- Start Error Handling Section -->
         {%include 'error-handle.html'%}
         <!-- End Error Handling Section -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <!-- Add Items Form -->
            <div class="card">
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Select Category</span>
        <select id="order-item-category" class="form-select" aria-label="Default select example">
            {%for cate in categories%}
            <option value="{{cate.id}}">{{cate.categ}}</option>
            {%endfor%}
          </select>
          <span class="input-group-text" id="basic-addon1">Item Name</span>
        <input id="order-item-name" type="text" class="form-control" placeholder="Item Name" aria-label="text" aria-describedby="basic-addon1">
      </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Serial</span>
        <input id="order-item-serial" type="text" class="form-control" placeholder="Serial" aria-label="text" aria-describedby="basic-addon1">
        <span class="input-group-text" id="basic-addon1">Quantitly</span>
        <input id="order-item-quantity" type="text" class="form-control" placeholder="Quantity" aria-label="text" aria-describedby="basic-addon1">
        
      </div>
      <button id="add-item-btn" class="btn btn-primary">Add To List</button>
    </div> <!-- End Add Items Form-->
        </div>
    </div>
<!-- Items Table -->
<div class="row">
    <form action="" method="post">
    <table id="order_items_table" class="table table-striped table-bordered table-hover text-center">
        <thead>
            <tr>
                <th>Category</th>
                <th>Item Name</th>
                <th>Serial</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
    <div class="input-group mb-3">
        <span class="input-group-text">Attachment</span>
        <input class='custom-file-input form-control' type="file">
        <button class="btn btn-primary">Save Order</button>
    </div>
</form>
</div>
<!-- End Items Table -->
</div>
</div>
</section>
{%endblock%}

uxapp/templates/stock/stock-item.html
<!-- Category Stock Items View Template -->
{% extends "dashboard.html" %}
{% block pcdetails %}
<div class="container">
    <div class="row">
         <!-- Start Error Handling Section -->
         {%include 'error-handle.html'%}
         <!-- End Error Handling Section -->
        <div class="col-12">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2><b>{{stock_item_cat.categ}}</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="#" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#addItem"><i class="bi bi-plus-lg"></i> <span>Add New Item</span></a>
                        <a href="#" class="btn btn-secondary"><i class="bi bi-file-earmark-spreadsheet"></i> <span>Export to Excel</span></a>
                    </div>
                </div>
            </div>
            <!-- Start Add Item -->
            <div class="modal fade" id="addItem" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add New Item</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{url_for('stock_routes.stockItem', st_item = stock_item_cat.id)}}" method="post">
                                <div class="mb-3">
                                    <label for="stockItem" class="col-form-label">Item Name</label>
                                    <input type="text" class="form-control" name="stockItem" id="add-stockItem"value="">
                                </div>
                                <div class="mb-3">
                                    <label for="add-serial" class="col-form-label">Serial</label>
                                    <input type="text" class="form-control" name="add-serial" id="add-serial" value="">
                                </div>
                                <div class="mb-3">
                                    <label for="add-quantity" class="col-form-label">Quantity</label>
                                    <input type="number" class="form-control" name="add-quantity" id="add-quantity"
                                        value="">
                                </div>
                                <div class="mb-3">
                                    <label for="add-pos" class="col-form-label">Position</label>
                                    <input type="text" class="form-control" name="add-pos" id="add-pos" value="">
                                </div>
                                <div class="mb-3">
                                    <label for="add-assi" class="col-form-label">Assign To</label>
                                    <input type="text" class="form-control" name="add-assi" id="add-assi" value="" placeholder="Biometric">
                                </div>
                                <div class="mb-3">
                                    <label for="add-comm" class="col-form-label">Comment</label>
                                    <textarea type="text" class="form-control" name="add-comm" id="add-comm" value=""></textarea>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                                        data-bs-toggle="tooltip" data-bs-placement="bottom"
                                        title="Cancel">Cancel</button>
                                    <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip"
                                        data-bs-placement="bottom" title="Move To Returned">Add <i
                                            class="bi bi-arrow-90deg-right"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Add Item -->
        </div>
        <div class="col-md-12">
            <table class="table table-striped text-center">
                <thead class="thead-dark">
                    <tr>
                        <th scope="row">#</th>
                        <th scope="row">Item</th>
                        <th scope="row">Serial</th>
                        <th scope="row">Quantity</th>
                        <th scope="row">Position</th>
                        <th scope="row">Assigned To</th>
                        <th scope="row">Comment</th>
                        <th scope="row"></th>
                    </tr>
                </thead>
                <tbody id="pcs_table">
                    {% for stock_item in stock_categs_items %}
                    <tr>
                        <th scope="col">{{ loop.index0 +1 }}</th>
                        <th scope="col">{{stock_item.item_name}}</th>
                        <th scope="col" class="serial">{{stock_item.serial}}</th>
                        <th scope="col">{{stock_item.quantity}}</th>
                        <th scope="col">{{stock_item.position}}</th>
                        <th scope="col" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{stock_item.agentstock.name}} {{stock_item.agentstock.l_name}}">{{stock_item.agentstock.bio}}</th>
                        <th scope="col">{{stock_item.comment}}</th>
                        <th scope="col"><a href="#" class="btn btn-primary edit-btn" data-bs-toggle="modal" data-bs-target="#editItem-{{stock_item.id}}"><i
                                    class="bi bi-pencil"></i></a></th>
                    </tr>
                                 <!-- Start Edit Item -->
             <div class="modal fade" id="editItem-{{stock_item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Edit {{stock_item.item_name}}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{{url_for('stock_routes.stockItemEdit')}}" method="post">
                                <div class="mb-3">
                                    <input type="hidden" class="form-control" name="edit-id" id="edit-id" value="{{stock_item.id}}">
                                    <input type="hidden" class="form-control" name="cat-id" id="cat-id" value="{{stock_item_cat.categ}}">
                                    <label for="stockItem" class="col-form-label">Item Name</label>
                                    <input type="text" class="form-control" name="stockItem" id="add-stockItem" value="{{stock_item.item_name}}">
                                </div>
                                <div class="mb-3">
                                    <label for="add-serial" class="col-form-label">Serial</label>
                                    <input type="text" class="form-control" name="add-serial" id="add-serial" value="{{stock_item.serial}}">
                                </div>
                                <div class="mb-3">
                                    <label for="add-quantity" class="col-form-label">Quantity</label>
                                    <input type="number" class="form-control" name="add-quantity" id="add-quantity"
                                        value="{{stock_item.quantity}}">
                                </div>
                                <div class="mb-3">
                                    <label for="add-pos" class="col-form-label">Position</label>
                                    <input type="text" class="form-control" name="add-pos" id="add-pos" value="{{stock_item.position}}">
                                </div>
                                <div class="mb-3">
                                    <label for="edit-assi" class="col-form-label">Assign To</label>
                                    <input type="text" class="form-control" name="edit-assi" id="edit-assi" value="{{stock_item.agentstock.bio}}" placeholder="Biometric">
                                </div>
                                <div class="mb-3">
                                    <label for="add-comm" class="col-form-label">Comment</label>
                                    <textarea type="textarea" class="form-control" name="add-comm" id="add-comm" value="{{stock_item.comment}}">{{stock_item.comment}}</textarea>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                                        data-bs-toggle="tooltip" data-bs-placement="bottom"
                                        title="Cancel">Cancel</button>
                                            <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip"
                                        data-bs-placement="bottom" title="Save">Save <i
                                            class="bi bi-arrow-90deg-right"></i></button>
                                </div>
                            </form>
                            <form action="{{url_for('stock_routes.stockItemDelete')}}" method="post">
                                <input type="hidden" class="form-control" name="delete-id" id="delete-id" value="{{stock_item.id}}">
                                <button type="submit" class="btn btn-danger" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Remove">Remove</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Edit Item -->
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

uxapp/templates/stock/stock-orders.html
<!-- Orders Boared Template -->
{% extends "dashboard.html" %}
{% block in_dashboard %}
<section class="orders-boared">
    <div class="col-md-12">
         <!-- Start Error Handling Section -->
         {%include 'error-handle.html'%}
         <!-- End Error Handling Section -->
        <div class="container-fluid">
           <!-- Start Add Category -->
        <div class="modal fade" id="new-stock-in-modal" tabindex="-1"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add New</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="" method="post" class="needs-validation" novalidate>
                <div class="form-group">
                  <label for="stock-in-group" class="col-form-label">Delivery Title</label>
                  <div class="input-group has-validation">
                  <input type="text" class="form-control"  name="delv-title" required>
                  <div class="invalid-feedback">
                    Please enter the title.
                  </div>
                </div>
                </div>
                <div class="form-group">
                  <div class="input-group has-validation"></div>
                  <label for="stock-in-group" class="col-form-label">Date</label>
                  <input id="date" class="form-control" type="date" name="delv-date" value="" required>
                  <div class="invalid-feedback">
                    Please enter the date.
                  </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Cancel">Cancel</button>
                  <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Edit">Add <i class="bi bi-arrow-90deg-right"></i></button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
       <!-- End Add Category -->
            <div class="table-responsive">
                <div class="table-wrapper">
                    <div class="table-title">
                        <div class="row">
                            <div class="col-sm-5">
                            </div>
                            <div class="col-sm-7">
                                <a href="#" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#new-stock-in-modal"><i class="bi bi-person-plus"></i> <span>Add New
                                        order</span></a>
                                <a href="#" class="btn btn-secondary"><i class="bi bi-file-earmark-spreadsheet"></i>
                                    <span>Export to Excel</span></a>
                                <a href="#" class="btn btn-secondary"><i class="bi bi-file-earmark-spreadsheet"></i>
                                    <span>Import From Excel</span></a>
                            </div>
                        </div>
                    </div>
                    <table id='hc-table' class="table table-striped table-bordered table-hover text-center">
                        <thead>
                            <tr>
                                <th class='col-1' tyle="width: 5%">#</th>
                                <th class='col-2' tyle="width: 10%">Order ID</th>
                                <th class='col-6' tyle="width: 62.5%">Title</th>
                                <th class='col-3' tyle="width: 22.5%">Date</th>
                            </tr>
                        </thead>
                        <tbody id="orders-tb">
                            {% for order in orders%}
                            <tr>
                                <td> {{ loop.index0 +1 }}</td>
                                <td><a href='{{url_for("stock_routes.stock_order_view", order_id=order.id)}}'>#{{order.id}}</a></td>
                                <td>{{order.title}}</td>
                                <td>
                                  {% if order.date%}
                                  {{order.date.strftime('%Y-%m-%d')}}
                                {%endif%}
                                </td>

                            </tr>
                       
                            {%endfor%}
                        </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</section>
<script>
  // Form Validation
(function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
</script>
{%endblock%}

uxapp/templates/stock/stock-view-order.html
<!-- Orders Boared Template -->
{% extends "dashboard.html" %}
{% block in_dashboard %}
<section class="orders-boared">
    <div class="col-md-12">
         <!-- Start Error Handling Section -->
         {%include 'error-handle.html'%}
         <!-- End Error Handling Section -->
<div class="container">
<!-- Items Table -->
<div class="row">
    <table id="order_items_table" class="table table-striped table-bordered table-hover text-center">
        <thead>
            <tr>
                <th>Category</th>
                <th>Item Name</th>
                <th>Serial</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
<form action="" method="post">
    <div class="input-group mb-3">
        <a href='{{url_for("stock_routes.stock_order_view", order_id = order_id)}}' class="btn btn-primary">Edit Order</a>
    </div>
</form>
<form action="" method="post">
    <div class="input-group mb-3">
        <button class="btn btn-danger">Delete Order</button>
    </div>
</form>
</div>
<!-- End Items Table -->
</div>
</div>
</section>
{%endblock%}