uxapp/main/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for, flash, jsonify
from flask_login import login_required
import datetime
from sqlalchemy import desc, extract
from uxapp.models import Users, wfh_pcs, Todolist

main = Blueprint('main', __name__)

#=========================
# Dashboard Route
#=========================
@main.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    dbusers = Users.query.order_by(Users.email)  
    # Statistics Queries 
    wfh_today = wfh_pcs.query.filter(wfh_pcs.wfhdate == datetime.datetime.today().strftime('%Y-%m-%d')).count()
    wfh_this_month = len(wfh_pcs.query.filter(extract('month', wfh_pcs.wfhdate) >= datetime.datetime.today().month,
                                extract('year', wfh_pcs.wfhdate) >= datetime.datetime.today().year).all())
    # print(len(wfh_this_month))
    if datetime.datetime.today().month == 1:
        l_month = 12
        l_year = datetime.datetime.today().year - 1
    else:
        l_month = datetime.datetime.today().month - 1
        l_year = datetime.datetime.today().year
    # print(l_month, l_year)
    wfh_last_month= len(wfh_pcs.query.filter(extract('month', wfh_pcs.wfhdate) >= l_month,
                                extract('year', wfh_pcs.wfhdate) >= l_year).all())
    wfh_this_year = len(wfh_pcs.query.filter(extract('year', wfh_pcs.wfhdate) >= datetime.datetime.today().year).all())
    wfh_last_year = len(wfh_pcs.query.filter(extract('year', wfh_pcs.wfhdate) == datetime.datetime.today().year - 1).all())
    # print(datetime.datetime.today().year - 1)
    
    return render_template("/dashboard.html", title="Dashboard", dashboard="active", dbusers = dbusers, wfh_today = wfh_today, wfh_this_month = wfh_this_month, wfh_last_month = wfh_last_month, wfh_this_year =wfh_this_year, wfh_last_year = wfh_last_year )

uxapp/pcs/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for, flash, jsonify, send_file
from flask_login import login_required
import os
import json
import pandas as pd 
from uxapp.config import engine, allowed_file
from uxapp.models import pcs
from uxapp import db

pcs_routes = Blueprint('pcs_routes', __name__)
#=========================
# PCs Details Route
#=========================
@pcs_routes.route("/pcdetails" , methods=['GET', 'POST'])
@login_required
def pcdetails():
    if request.method == "POST":
        if 'addpc' in request.form:
            site = request.form['site']
            build = request.form['build']
            floor = request.form['floor']
            pc_no = request.form['pc_no']
            pc_host = request.form['pc_host']
            ip = request.form['pc_ip']
            pbxuser = request.form['pbxuser']
            ciscodid = request.form['ciscodid']
            
            Pc= pcs.query.filter_by(id = pc_no).first()
            PC_name = pcs.query.filter_by(hostname = pc_host).first()
            if Pc is None:
                if pcs.query.filter_by(hostname = pc_host).first() is None:
                    Pc = pcs(site = site, build = build, floor = floor, station = pc_no, hostname = pc_host,ip = ip, pbxuser = pbxuser, ciscodid = ciscodid)
                    db.session.add(Pc)
                    db.session.commit()
                    return jsonify({'success':'PC Added Successfuly'})
                    flash('PC Added Successfuly', 'alert-success')
                else:    
                    flash('PC Is Already Exist In Table','alert-danger')  
                    return jsonify({'error':'PC Is Already Exist In Table'}) 
            else:    
                return jsonify({'error':'PC Is Already Exist In Table'}) 
                flash('PC Is Already Exist In Table', 'alert-danger')   
        elif 'editpc' in request.form:
            e_id = request.form['pc-id']
            e_site = request.form['site']
            e_build = request.form['build']
            e_floor = request.form['floor']
            e_station = request.form['station']
            e_hostname = request.form['hostname']
            e_ip = request.form['ip']
            e_bpxuser = request.form['pbxuser']
            e_ciscodid = request.form['ciscodid']
            try:
                pc = pcs.query.filter_by(id = e_id).first()
                pc.site = e_site
                pc.build = e_build
                pc.floor = e_floor
                pc.station = e_station
                pc.hostname = e_hostname
                pc.ip = e_ip
                pc.pbxuser = e_bpxuser
                pc.ciscodid = e_ciscodid
                db.session.commit()
                flash('PC Updated Successfully', 'alert-success')
                return redirect(url_for('pcs_routes.pcdetails'))
            except:
                flash('Error, Please Try Again', 'alert-danger')
                return redirect(url_for('pcs_routes.pcdetails'))
    pcs_table =  pcs.query.order_by(pcs.id) 
    return render_template("/pcdetails.html", title="PCs Details", pcdetails="active", pcs_table = pcs_table)
#====================================
# PCS Pagination Route
#====================================    
@pcs_routes.route("/pcdetails/<int:page_num>" , methods=['GET', 'POST'])
@login_required
def pcpagin(page_num):
    pcs_table = pcs.query.order_by(pcs.id) 
    return render_template("/pcdetails.html", title="PCs Details", pcdetails="active", pcs_table = pcs_table, page_num = page_num)    
#====================================
# Import PCs from Excel Sheet  Route
#====================================
@pcs_routes.route("/upload-pcs" , methods=['GET', 'POST'])
@login_required
def uploadpcs():
    if request.method == "POST":
        upload_file = request.files.get('pcexc')
        if upload_file and allowed_file(upload_file.filename):
            if upload_file.filename != '':
                file_path = os.path.join(pcs_routes.config["UPLOAD_FOLDER"], upload_file.filename)
                upload_file.save(file_path)
                data=pd.read_excel(upload_file)
                df = pd.DataFrame(data)
                duplicated = df[df.duplicated('HOSTNAME')]
                ckeck = data.values.tolist()
                for a,b,c,d,e,f,g,h in ckeck:
                    try:
                        if pcs.query.filter_by(hostname = e).all() != [] and pcs.query.filter_by(pbxuser = g).all() != [] and pcs.query.filter_by(ciscodid = h).all() != []:
                            flash('There is Dublicated Hostname > '+ e, 'alert-danger')
                            flash('There is Dublicated DID User > '+ str(g).rsplit('.', -1)[-1], 'alert-danger')
                            flash('There is Dublicated DID Extention > '+ str(h).rsplit('.', -1)[-1], 'alert-danger')
                        else:
                            data.to_sql('pcs', con = engine, if_exists = 'append', index = False)
                            flash('Excel Sheet Imported Successfully', 'alert-success')
                            return redirect(url_for('pcs_routes.pcdetails'))
                    except:
                        flash('Error: There is Dublicated Items In your Excel Sheet or Column Names incorrect ', 'alert-danger')
                        dubl_json = duplicated.to_json(orient="split")
                        parsed = json.loads(dubl_json)
                        # print(json.dumps(parsed, indent=4))
                        for pc in parsed['data']:
                            if pc[4] is not None:
                                flash( pc[4]  , 'alert-danger')                        
                        return redirect(url_for('pcs_routes.pcdetails'))
            else:
                flash('Faild: Please Import "slsx" Files', 'alert-danger')
        else:
            flash('Faild: File extention not valid, Please Import "slsx" Files', 'alert-danger')
            return redirect(url_for('pcs_routes.pcdetails'))         
        
        return redirect(url_for('pcs_routes.pcdetails'))
#=====================================
# Export PCs from Excel Sheet  Route
#=====================================
@pcs_routes.route("/export-pcs" , methods=['GET', 'POST'])
@login_required
def exportpcs():
        pcs_table = pd.read_sql_query('SELECT site, build,floor,station,hostname, ip, pbxuser, ciscodid FROM pcs', engine)
        df1 = pd.DataFrame(pcs_table)
        # writing to Excel
        df1.to_excel("static/download/HostNames Inventory.xlsx", sheet_name='Alex')
        file_path = 'static/download/HostNames Inventory.xlsx'
        download = send_file(file_path, as_attachment=True)
        return download 
#=========================        
# Edit Pc Route
#=========================
@pcs_routes.route("/edit-pc" , methods=['GET', 'POST'])
@login_required
def edit_pc():
    return render_template("/edit-pc.html", title="Edit PC")

uxapp/requests/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for, flash, jsonify, send_file
from flask_login import login_required, current_user
from sqlalchemy import desc
import datetime
from uxapp.models import wfh_pcs, Agents, Itcheck,Facilitycheck, Departure, Requests, Securitycheck,Ticket_cat, Ticket_subcat, Tickets
from uxapp import db
req_routes = Blueprint('req_routes', __name__)

#=========================
# Requests Route
#=========================
@req_routes.route("/request" , methods=['GET', 'POST'])
@login_required
def requests():
    sub_id = request.form.get('service_id')
    ticket_cat = Ticket_cat.query.all()
    ticket_sub_cat = Ticket_subcat.query.filter_by(id = 1).all()
    if request.method == 'POST':
        title = request.form['title']
        if 'dep_req_form' in request.form:
            bio = request.form['bio']
            agent_qu = Agents.query.filter_by(bio = bio).first()
            if agent_qu:
                add_dep = Departure(agent = agent_qu.id)
                db.session.add(add_dep)
                db.session.flush()
                send_facility = Facilitycheck(req_no = add_dep.id)
                send_it = Itcheck(req_no = add_dep.id)
                send_security = Securitycheck(req_no = add_dep.id)
                add_request = Requests(dep_req = add_dep.id, req_title = title, req_date = datetime.datetime.today(), req_by = current_user.id, req_type = 1, depart_req = current_user.depart)
                db.session.add(add_request)
                db.session.add(send_facility)
                db.session.add(send_it)
                db.session.add(send_security)
                db.session.commit()
                flash('Request Created Successfully', 'alert-success')
            else:
                flash('Error, Make sure that the agent is exist', 'alert-danger')
        if 'new_ticket' in request.form:
            service = request.form.get('service_id')
            sub_service = request.form.get('servicesubcategory_id')
            impact = request.form.get('impact')
            urgency = request.form.get('urgency')
            t_title = request.form.get('title')
            description = request.form.get('description')
            if request.method == "POST":
                add_ticket = Tickets(sub_service = sub_service, impact = impact, urgency = urgency, title = t_title, description = description)
                db.session.add(add_ticket)
                db.session.flush()
                add_request = Requests(ticket_req = add_ticket.id, req_title = t_title, req_date = datetime.datetime.today(), req_by = current_user.id, req_type = 3, depart_req = current_user.depart)
                db.session.add(add_request)
                db.session.commit()

    # all_req = Departure.query.order_by(Departure.id).all()
    all_req = Requests.query.order_by(desc(Requests.id)).all()
    all_dep_req = Requests.query.filter_by(depart_req = current_user.depart).all()
    all_opend_req = Requests.query.filter_by(statue = None).all()
    all_resolved_req = Requests.query.filter_by(statue = 'resolved').all()
    all_closed_req = Requests.query.filter_by(statue = 'closed').all()
    tickets = Tickets.query.order_by(Tickets.id).all()
    return render_template("/requests.html", title="Requests", requests = 'active', all_req = all_req, all_opend_req = all_opend_req, all_closed_req= all_closed_req, all_resolved_req = all_resolved_req , all_dep_req = all_dep_req, ticket_cat = ticket_cat, ticket_sub_cat = ticket_sub_cat, tickets = tickets)
#======================
# Requests Edit Route
#======================
@req_routes.route("/request/<int:id>" , methods=['GET', 'POST'])
@login_required
def requests_edit(id):
    req = Requests.query.filter_by(id = id).first()
    dep = None
    have_pc = None
    if req.dep_req is not None:
        dep = Departure.query.filter_by(id = req.dep_req).first()
        have_pc = wfh_pcs.query.filter_by(agent = dep.agent).first()
    if request.method == 'POST':
        def req_check(to_check): # This function for generate True or False from form checkbox
            return True if to_check != None else False
        if 'facility-check' in request.form:
            edit_req = Facilitycheck.query.filter_by(req_no = dep.id).first()
            pc = request.form.get('pc')
            screens = request.form.get('screens')
            desktop = request.form.get('desktop')
            labtop = request.form.get('labtop')
            cebox = request.form.get('cebox')
            jack = request.form.get('jack')
            usb = request.form.get('usb')
            rj11 = request.form.get('rj11')
            on_cell = request.form.get('on-cell')
            proffess = request.form.get('proffess')
            locker = request.form.get('locker')
            office = request.form.get('office')
            comment = request.form.get('comment')
            # print(req_check(screens))
            try:
                edit_req.pc = req_check(pc)
                edit_req.screens = req_check(screens)
                edit_req.desktop = req_check(desktop)
                edit_req.labtop = req_check(labtop)
                edit_req.cebox = req_check(cebox)
                edit_req.jack = req_check(jack)
                edit_req.usb = req_check(usb)
                edit_req.rj11 = req_check(rj11)
                edit_req.on_cell = req_check(on_cell)
                edit_req.proffess = req_check(proffess)
                edit_req.locker = req_check(locker)
                edit_req.office = req_check(office)
                edit_req.comment = comment
                dep.facility_check = edit_req.id
                if dep.it_check != None or dep.it_check != '':
                    dep.statue = 'resolved'
                    req.statue = 'resolved'
                db.session.commit()
                flash('Request Updated', 'alert-success')
                return redirect(request.referrer)
            except:
                flash('Error, Please Try Again', 'alert-danger')
                return redirect(request.referrer)
        elif 'it-check' in request.form:
            edit_req = Itcheck.query.filter_by(req_no = dep.id).first()
            access = request.form.get('access')
            internal_email = request.form.get('internal-email')
            external_email = request.form.get('external-email')
            vpn = request.form.get('vpn')
            comment = request.form.get('comment')
            try:
                edit_req.access = req_check(access)
                edit_req.internal_email = req_check(internal_email)
                edit_req.external_email = req_check(external_email)
                edit_req.vpn = req_check(vpn)
                edit_req.comment = comment  
                dep.it_check = edit_req.id
                if dep.facility_check != None or dep.facility_check != '':
                    dep.statue = 'resolved'
                    req.statue = 'resolved'
                db.session.commit()
                flash('Request Updated', 'alert-success')
                return redirect(request.referrer)
            except:
                flash('Error, Please Try Again', 'alert-danger')
                return redirect(request.referrer)
        elif 'close-req' in request.form:
            try:
                cls_req = Requests.query.filter_by(id = request.form['close-req']).first()
                cls_req.statue = 'closed'
                db.session.commit()
                flash('Ticket Closed', 'alert-success')
                return redirect(request.referrer)
            except:
                flash('Error, Please Try Again', 'alert-danger')
                return redirect(request.referrer)
    return render_template("/requests-edit.html", title="Edit Request", req = req, have_pc = have_pc, dep = dep)
    
@req_routes.route("/request/details" , methods=['GET', 'POST'])
@login_required
def requests_details():
    if request.method == 'POST':
        sub_id = request.form['data']

    # ticket_cat = Ticket_cat.query.order_by(id).all()
        ticket_sub_cat = Ticket_subcat.query.filter_by(sub_cat = sub_id).all()
        sub_cat = {}
        for tic in ticket_sub_cat:
            sub_cat[tic.id] = tic.name

    return jsonify(sub_cat)

uxapp/schadul/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for, flash, jsonify
from flask_login import login_required
from uxapp.models import Leaves

schadul_routes = Blueprint('scadul_routes', __name__)

@schadul_routes.route('/schadul', methods=['GET', 'POST'])
@login_required
def schadul():
    leaves = Leaves.query.all()
    return render_template('/schadul.html', title="Schadul", schadul="active", leaves = leaves)

uxapp/templates/actions-nav.html
{% if url_for('stock_routes.stock') == request.path:%}
<div class="categ-ctrl text-end">
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addCateg">
      <i class="bi bi-plus-square"></i>
    </button>
</div>
{%endif%}

{% if url_for('req_routes.requests') == request.path:%}
<div class="categ-ctrl text-end">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new-dep">
    New Depareture Request
  </button>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new-ticket">
    New Ticket
  </button>
</div>
{%endif%}

uxapp/templates/pcdetails.html
<!-- PCs Details Template -->
{% extends "dashboard.html" %}
{% block pcdetails %}
<div class="container-fluid">
    <div class="row">
        <!-- Add Pc Section -->
        <div class="col-12">
            <div class="edit-for">
                <h3>Add New PC</h3>
            </div>
              <!-- Start Error Handling Section -->
              {%include 'error-handle.html'%}
              <!-- End Error Handling Section -->
            <form id="add_pc" action="" method="post" class="edit-item shadow p-3 mb-5 bg-body rounded">
                <div class="container-fluid">
                    <div class="row">
                        <input type="hidden" name="addpc">
                        <div class="col-md-3">
                            <label for="site" class="col-form-label">Site</label>
                            <input type="text" class="form-control" name="site" id="e-site"
                                value="">
                        </div>
                        <div class="col-md-3">
                            <label for="build" class="col-form-label">Build</label>
                            <input type="text" class="form-control" name="build"
                                id="e-build" value="">
                        </div>
                        <div class="col-md-3">
                            <label for="floor" class="col-form-label">Floor</label>
                            <input type="text" class="form-control" name="floor"
                                id="e-floor" value="">
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label for="pc_number" class="form-label">PC Number</label>
                                <input id="pc_number" type="number" name="pc_no" class="form-control" placeholder="55"
                                    value="" required>
                            </div>
                        </div>
                        <div class="col-md-3">
                                <label for="pc_host" class="form-label">PC Host Name</label>
                                <input id="pc_host" name="pc_host" class="form-control" placeholder="EG-A0-F2-50"
                                    value="" required>
                        </div>
                        <div class="col-md-3">
                            <label for="pc_ip" class="form-label">PC IP</label>
                            <input id="pc_ip" name="pc_ip" class="form-control" placeholder=""
                                value="" required>
                    </div>
                        <div class="col-md-3">
                            <label for="pbxuser" class="form-label">DID User</label>
                            <input id="pbxuser" name="pbxuser" class="form-control" placeholder="30156" value="">
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label for="ciscodid" class="form-label">DID Ext</label>
                                <input id="ciscodid" name="ciscodid" class="form-control" placeholder="632564" value="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-controls">
                    <button class="btn btn-primary edit-btn" data-bs-toggle="tooltip" data-bs-placement="bottom"
                        title="Submit Edits"><i class="bi bi-check"></i></button>
                    <!-- <button class="btn btn-primary" type="submit">
                                <span class="aj-spinner spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                <i class="bi bi-check aj-icon"></i>
                              </button> -->
                </div>

            </form>
            <!-- Import PCs From Excel Sheet -->
            <form id="add-pc-exc" action="{{url_for('pcs_routes.uploadpcs')}}" method="post" enctype="multipart/form-data" class="edit-item shadow p-3 mb-5 bg-body rounded">
            <div class="custom-file">
                <h3> Import From Excel Sheet</h3>
                <input type="file" class="custom-file-input" id="pcexc" name="pcexc">
                <label class="custom-file-label" for="pcexc">Choose file</label>
                <!-- <button class="btn btn-primary edit-btn" data-bs-toggle="tooltip" data-bs-placement="bottom"
                        title="Submit Edits"><i class="bi bi-check"></i></button> -->
                        <button class="btn btn-primary" type="submit">
                            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            Upload
                          </button>
              </div>
            </form>
            <!-- End Import From Excel -->
        </div>
        <!-- End Add Pc Section -->

        <div class="col-md-12">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2><b>{{title}}</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="#" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#addItem"><i class="bi bi-plus-lg"></i> <span>Add New Item</span></a>
                        <a href="{{url_for('pcs_routes.exportpcs')}}" class="btn btn-secondary"><i class="bi bi-file-earmark-spreadsheet"></i> <span>Export to Excel</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="row">#</th>
                        <th scope="row">Site</th>
                        <th scope="row">Build</th>
                        <th scope="row">Floor</th>
                        <th scope="row">Station No</th>
                        <th scope="row">HostName</th>
                        <th scope="row">IP Adress</th>
                        <th scope="row">PBX User</th>
                        <th scope="row">cisco DID</th>
                        <th scope="row"></th>
                    </tr>
                </thead>
                <tbody id="pcs_table">
                    {% for pc in pcs_table %}
                    <tr>
                        <th scope="col">{{ loop.index0 +1 }}</th>
                        <th scope="col">{{pc.site}}</th>
                        <th scope="col">{{pc.build}}</th>
                        <th scope="col">{{pc.floor}}</th>
                        <th scope="col">{{pc.station}}</th>
                        <th scope="col">{{pc.hostname}}</th>
                        <th scope="col">{{pc.ip}}</th>
                        <th scope="col">{{pc.pbxuser}}</th>
                        <th scope="col">{{pc.ciscodid}}</th>
                        <th scope="col"><a href="#" class="btn btn-primary edit-btn" data-bs-toggle="modal" data-bs-target="#editpc-{{pc.id}}"><i
                                    class="bi bi-pencil"></i></a>
                                                        <!-- Start Edit PC -->
                        <div class="modal fade" id="editpc-{{pc.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Edit {{pc.hostname}}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="" method="post">
                                        <div class="row mb-3">
                                            <input type="hidden" name="editpc">
                                            <input type="hidden" class="form-control" name="pc-id"
                                                id="pc-id" value="{{pc.id}}">
                                                <div class="col-md-6">
                                                    <label for="site" class="col-form-label">Site</label>
                                                    <input type="text" class="form-control" name="site"
                                                        id="e-site" value="{{pc.site}}">
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="build" class="col-form-label">Build</label>
                                                    <input type="text" class="form-control" name="build"
                                                        id="e-build" value="{{pc.build}}">
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="floor" class="col-form-label">Floor</label>
                                                    <input type="text" class="form-control" name="floor"
                                                        id="e-floor" value="{{pc.floor}}">
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="station" class="col-form-label">Station No</label>
                                                    <input type="text" class="form-control" name="station"
                                                        id="e-station" value="{{pc.station}}">
                                                </div>
                                            <div class="col-md-6">
                                                <label for="hostname" class="col-form-label">Hostname</label>
                                                <input type="text" class="form-control" name="hostname"
                                                    id="e-hostname" value="{{pc.hostname}}">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="ipadress" class="col-form-label">IP Adress</label>
                                                <input type="text" class="form-control" name="ip"
                                                    id="e-ip" value="{{pc.ip}}">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="bpxuser" class="col-form-label">PBX User</label>
                                                <input type="text" class="form-control" name="pbxuser"
                                                    id="e-pbxuser" value="{{pc.pbxuser}}">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="ciscodid" class="col-form-label">Cisco DID</label>
                                                <input type="text" class="form-control" name="ciscodid"
                                                    id="e-ciscodid" value="{{pc.ciscodid}}">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-bs-dismiss="modal" data-bs-toggle="tooltip"
                                                data-bs-placement="bottom" title="Cancel">Cancel</button>
                                            <button type="submit" class="btn btn-primary"
                                                data-bs-toggle="tooltip" data-bs-placement="bottom"
                                                title="Update Pc">Update PC <i
                                                    class="bi bi-arrow-90deg-right"></i></button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- End Edit PC -->
                                </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          
        </div>
    </div>
</div>
{%endblock%}

uxapp/templates/search-form.html
<div class="col-md-12">
    <form class="search-form" action="/search" method="GET">
        <div class="row">
            <div class="col-9">
                <input id="search" name="search" class="search form-control" type="text" placeholder="search">
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-primary mb-2"><i class="bi bi-search"></i></button>
            </div>
        </div>
    </form>
</div>